{
    "openapi": "3.0.0",
    "info": {
        "title": "API",
        "description": "API",
        "version": "1.0.0",
        "contact": {
            "name": "Gustavo Côrtes",
            "email": "gpcortes@gmail.com"
        }
    },
    "basePath": "/users",
    "tags": [
        {
            "name": "users",
            "description": "Gerenciamento de usuários"
        }
    ],
    "schemes": [
        "http"
    ],
    "paths": {
        "/users": {
            "post": {
                "tags": [
                    "users"
                ],
                "summary": "Cria um novo usuário.",
                "requestBody": {
                    "description": "Campos obrigatórios pqara criação de um usuário.",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/request/User"
                            },
                            "example": {
                                "name": "Gustavo Côrtes",
                                "email": "gpcortes@gmail.com"
                            },
                            "required": true
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Operação realizada com sucesso.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/response/User"
                                },
                                "example": {
                                    "id": "fa8ecb07-718e-47c4-97e2-d20a6d1ad332",
                                    "name": "Gustavo Côrtes",
                                    "admin": false,
                                    "email": "gpcortes@gmail.com",
                                    "created_at": "2020-05-05T18:00:00.000Z",
                                    "updated_at": "2020-05-05T18:00:00.000Z"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Email já está sendo utilizado.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Error"
                                },
                                "example": {
                                    "message": "This email is already in use."
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "Retorna todos os usuários.",
                "description": "Somente usuário admin pode acessar.",
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "header",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "uuid"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operação realizada com sucesso.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/response/User"
                                },
                                "example": [
                                    {
                                        "id": "fa8ecb07-718e-47c4-97e2-d20a6d1ad332",
                                        "name": "Gustavo Côrtes",
                                        "admin": false,
                                        "email": "gpcortes@gmail.com",
                                        "created_at": "2020-05-05T18:00:00.000Z",
                                        "updated_at": "2020-05-05T18:00:00.000Z"
                                    },
                                    {
                                        "id": "fa8ecb07-718e-47c4-97e2-d20a6d1ad333",
                                        "name": "Thiago Côrtes",
                                        "admin": false,
                                        "email": "tgpcortes@gmail.com",
                                        "created_at": "2020-05-05T18:00:00.000Z",
                                        "updated_at": "2020-05-05T18:00:00.000Z"
                                    }
                                ]
                            }
                        }
                    },
                    "400": {
                        "description": "Usuário sem permissão ou não encontrado.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Error"
                                },
                                "example": {
                                    "error": "You need to be an administratir to list all users."
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{user_id}": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "Retorna um usuário específico.",
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "required": true,
                        "description": "ID do usuário."
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operação realizada com sucesso.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/response/User"
                                },
                                "example": {
                                    "id": "fa8ecb07-718e-47c4-97e2-d20a6d1ad332",
                                    "name": "Gustavo Côrtes",
                                    "admin": false,
                                    "email": "gpcortes@gmail.com",
                                    "created_at": "2020-05-05T18:00:00.000Z",
                                    "updated_at": "2020-05-05T18:00:00.000Z"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Usuário não encontrado.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Error"
                                },
                                "example": {
                                    "error": "User not found."
                                }
                            }
                        }
                    }
                }
            }
        },
        "/user/{user_id}/admin": {
            "patch": {
                "tags": [
                    "users"
                ],
                "summary": "Torna admin um usuário.",
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "uuid"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Operação realizada com sucesso.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/response/User"
                                },
                                "example": {
                                    "id": "fa8ecb07-718e-47c4-97e2-d20a6d1ad332",
                                    "name": "Gustavo Côrtes",
                                    "admin": true,
                                    "email": "gpcortes@gmail.com",
                                    "created_at": "2020-05-05T18:00:00.000Z",
                                    "updated_at": "2020-05-05T18:00:00.000Z"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Usuário não encontrado.",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/definitions/Error"
                                },
                                "example": {
                                    "error": "User not found."
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "request": {
            "User": {
                "type": "object",
                "properties": {
                    "username": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    }
                }
            }
        },
        "response": {
            "User": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "admin": {
                        "type": "boolean"
                    },
                    "email": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "date"
                    },
                    "updated_at": {
                        "type": "date"
                    }
                }
            }
        },
        "Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}